name: 'Auto Merge to gh-pages'

on:
  push:
    branches:
      - main
jobs:
  auto-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Auto Merge
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        stable_branch: 'main'
        development_branch: 'gh-pages'
        allow_ff: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
